import os
import re

# String arrayi içindeki cümleleri al
cümleler = [
        "mówię wysoki raz jeszcze",
        "mówię gniew raz jeszcze",
        "mówię cichy raz jeszcze",
        "mówię uzbrojony raz jeszcze",
        "mówię oszustwo raz jeszcze",
        "mówię klucz raz jeszcze",
        "mówię dzwon raz jeszcze",
        "mówię pokład raz jeszcze",
        "mówię zakres raz jeszcze",
        "mówię groźba raz jeszcze",
        "mówię krawat raz jeszcze",
        "mówię skłonny raz jeszcze",
        "mówię zwykły raz jeszcze",
        "mówię sąsiad raz jeszcze",
        "mówię społeczny raz jeszcze",
        "mówię użyteczny raz jeszcze",
        "mówię szeroki raz jeszcze",
        "mówię porażka raz jeszcze",
        "mówię nienawiść raz jeszcze",
        "mówię złość raz jeszcze",
        "mówię różowy raz jeszcze",
        "mówię wrogość raz jeszcze",
        "mówię wybór raz jeszcze",
        "mówię kiepski raz jeszcze",
        "mówię brama raz jeszcze",
        "mówię odpowiedni raz jeszcze",
        "mówię obrzydliwy raz jeszcze",
        "mówię ponury raz jeszcze",
        "mówię środkowy raz jeszcze",
        "mówię godzina raz jeszcze",
        "mówię suchy raz jeszcze",
        "mówię kłamstwo raz jeszcze",
        "mówię strona raz jeszcze",
        "mówię szorstki raz jeszcze",
        "mówię malutki raz jeszcze",
        "mówię gładki raz jeszcze",
        "mówię gorączka raz jeszcze",
        "mówię smutny raz jeszcze",
        "mówię gwałt raz jeszcze",
        "mówię powód raz jeszcze",
        "mówię martwy raz jeszcze",
        "mówię papieros raz jeszcze",
        "mówię chwila raz jeszcze",
        "mówię ulica raz jeszcze",
        "mówię wątek raz jeszcze",
        "mówię decydujący raz jeszcze",
        "mówię kaszel raz jeszcze",
        "mówię właściwy raz jeszcze",
        "mówię głupi raz jeszcze",
        "mówię ślepy raz jeszcze",
        "mówię szachy raz jeszcze",
        "mówię możliwość raz jeszcze",
        "mówię tożsamość raz jeszcze",
        "mówię średni raz jeszcze",
        "mówię nowotwór raz jeszcze",
        "mówię strata raz jeszcze",
        "mówię zakładnik raz jeszcze",
        "mówię nagły raz jeszcze",
        "mówię strach raz jeszcze",
        "mówię trucizna raz jeszcze",
        "mówię korzeń raz jeszcze",
        "mówię płuco raz jeszcze",
        "mówię gruby raz jeszcze",
        "mówię samolubny raz jeszcze",
        "mówię okrągły raz jeszcze",
        "mówię wspólny raz jeszcze",
        "mówię nieznośny raz jeszcze",
        "mówię główny raz jeszcze",
        "mówię początek raz jeszcze",
        "mówię ciasny raz jeszcze",
        "mówię prosty raz jeszcze",
        "mówię wściekły raz jeszcze",
        "mówię bieda raz jeszcze",
        "mówię marynarz raz jeszcze",
        "mówię klęska raz jeszcze",
        "mówię zabójca raz jeszcze",
        "mówię zmęczenie raz jeszcze",
        "mówię tłusty raz jeszcze",
        "mówię zabójczy raz jeszcze",
        "mówię głuchy raz jeszcze",
        "mówię zemsta raz jeszcze",
        "mówię powinność raz jeszcze",
        "mówię codzienny raz jeszcze",
        "mówię próba raz jeszcze",
        "mówię blady raz jeszcze",
        "mówię rodzaj raz jeszcze",
        "mówię grzech raz jeszcze",
        "mówię złamany raz jeszcze",
        "mówię powódź raz jeszcze",
        "mówię krótki raz jeszcze",
        "mówię pająk raz jeszcze",
        "mówię powaga raz jeszcze",
        "mówię drażliwy raz jeszcze",
        "mówię słaby raz jeszcze",
        "mówię śmiertelny raz jeszcze",
        "mówię sztywny raz jeszcze",
        "mówię bękart raz jeszcze",
        "mówię obowiązek raz jeszcze",
        "mówię skąpy raz jeszcze",
        "mówię tajemnica raz jeszcze",
        "mówię obecny raz jeszcze",
        "mówię pojazd raz jeszcze",
        "mówię dowolny raz jeszcze",
        "mówię dziedzina raz jeszcze",
        "mówię żebrak raz jeszcze",
        "mówię umierający raz jeszcze",
        "mówię grypa raz jeszcze",
        "mówię bezradny raz jeszcze",
        "mówię wąski raz jeszcze",
        "mówię młotek raz jeszcze",
        "mówię krwawy raz jeszcze",
        "mówię żółty raz jeszcze",
        "mówię nagrobek raz jeszcze",
        "mówię cienki raz jeszcze",
        "mówię ogólny raz jeszcze",
        "mówię brązowy raz jeszcze",
        "mówię uszkodzony raz jeszcze",
        "mówię dorosły raz jeszcze",
        "mówię szczur raz jeszcze",
        "mówię wypadek raz jeszcze",
        "mówię pryszcz raz jeszcze",
        "mówię rozpacz raz jeszcze",
        "mówię leniwy raz jeszcze",
        "mówię srebrny raz jeszcze",
        "mówię indyk raz jeszcze",
        "mówię szary raz jeszcze",
        "mówię dawny raz jeszcze",
        "mówię samotny raz jeszcze",
        "mówię fioletowy raz jeszcze",
        "mówię niepewność raz jeszcze",
        "mówię obrażony raz jeszcze",
        "mówię narzędzie raz jeszcze",
        "mówię pogrzeb raz jeszcze",
        "mówię zasada raz jeszcze",
        "mówię żołądek raz jeszcze",
        "mówię hańba raz jeszcze",
        "mówię zmienny raz jeszcze",
        "mówię brudny raz jeszcze",
        "mówię pijany raz jeszcze",
        "mówię tchórzliwy raz jeszcze",
        "mówię równowaga raz jeszcze",
        "mówię płaszcz raz jeszcze",
        "mówię ciężki raz jeszcze",
        "mówię próżny raz jeszcze",
        "mówię jabłko raz jeszcze",
        "mówię truskawka raz jeszcze",
        "mówię malina raz jeszcze",
        "mówię gruszka raz jeszcze",
        "mówię borówka raz jeszcze",
        "mówię brzoskwa raz jeszcze",
        "mówię brzoskwinia raz jeszcze",
        "mówię cytryna raz jeszcze",
        "mówię ananas raz jeszcze",
]

# Cümleleri alfabetik olarak sırala
cümleler.sort()

# Wav dosyalarının bulunduğu dizin
wav_dizin = 'Projects/audio/0001'

# Wav dosyalarını al
wav_dosyaları = [dosya for dosya in os.listdir(wav_dizin) if dosya.endswith('.wav')]

# Wav dosyalarını alfabetik olarak sırala
wav_dosyaları.sort()

# Wav dosyalarının isimlerini cümlelerle değiştir
for i, dosya in enumerate(wav_dosyaları):
    yeni_isim = f"{i+2:04d}item_{cümleler[i]}.wav"
    eski_yol = os.path.join(wav_dizin, dosya)
    yeni_yol = os.path.join(wav_dizin, yeni_isim)
    os.rename(eski_yol, yeni_yol)
